---
apiVersion: v1
kind: Pod
metadata:
  name: cs370pod
  labels:
    name: cs370pod
spec:
  containers:
  - name: riverapi
    image: hjdachel/cs370proj
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cs370svc
  labels:
    name: cs370svc
spec:
  type: NodePort
  selector: 
    name: cs370pod
  ports:
  - name: http
    protocol: TCP
    targetPort: 3000
    port: 80
    nodePort: 30001